spring:
  profiles:
    default: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1111
    url: jdbc:mysql://host.docker.internal:3306/mydb
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: cache-server
      port: 6379
logging:
  level:
    org.springframework.cache: trace

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://instagram-db.c9ecw6e204ye.ap-northeast-2.rds.amazonaws.com:3306/mydb
    password: password
    username: admin
  data:
    redis:
      host: instagram-cahe-server.s4yek6.ng.0001.apn2.cache.amazonaws.com
      port: 6379

